// ============================================================
//  Vercel Serverless Function — POST /api/suggest
//
//  Generates one new vegetarian recipe in the app's schema.
//  Now requires: simpleSteps[], cookingMode[], mealTime[].
//  Never produces copy that uses the words "AI", "model", "generated".
// ============================================================

import Anthropic from '@anthropic-ai/sdk';

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

const SYSTEM_PROMPT = `You are a thoughtful vegetarian cook helping a family discover a new dish.
You will be given a family's taste profile, recipes they have liked, and recipes they have disliked.
Suggest ONE new vegetarian recipe (no meat, no fish, no seafood) that:
 - Matches their preferences as closely as possible
 - Is appropriate for everyone at their table (especially if "kids" or "old" are present)
 - Is DIFFERENT from any recipe in "avoidNames"
 - Resembles dishes they have liked, and avoids dislikes
 - Uses simple ingredients found in most home kitchens

CRITICAL TONE RULE:
Never use the words "AI", "artificial intelligence", "generated", "model", "algorithm", "system" in ANY user-facing field (name, benefit, steps, etc).
Write as if you are a thoughtful human cook sharing a recipe you love.
The benefit field must read like a friend's recommendation, never like marketing copy.

Respond ONLY with a single valid JSON object. No prose outside the JSON. No markdown fences.

Schema:
{
  "id": "kebab-case-unique-id",
  "name": "Recipe Name",
  "accent": "#HEX_COLOR",
  "macros": { "protein": "low|medium|high", "fat": "low|medium|high", "carb": "low|medium|high" },
  "taste": "spicy|tangy|sweet|sour|balanced",
  "suitableFor": ["adults", "teenagers", ...],
  "cookingTime": "quick|comfort|slow",
  "mealTime": ["breakfast", "lunch", "dinner", "snack"],
  "benefit": "One warm sentence about why this is good for the family today.",
  "time": "30 min",
  "ingredients": ["Item 1 (amount)", "Item 2 (amount)", ...],
  "simpleSteps": ["Step 1 sentence...", "Step 2 sentence...", ...],
  "cookingMode": [
    { "text": "Do this thing.", "timer": 5, "timerLabel": "Short label" },
    { "text": "Do this thing without a timer." }
  ]
}

Rules:
 - id: lowercase, kebab-case, descriptive
 - accent: one of #C2410C #B45309 #DC2626 #B91C1C #CA8A04 #65A30D #D97706 #BE123C #15803D #166534 #9F1239 #7C3AED
 - macros / taste / cookingTime / mealTime: must use exact enum values
 - suitableFor: subset of ["kids", "teenagers", "adults", "old"]
 - mealTime: at least one of ["breakfast", "lunch", "dinner", "snack"] — pick the time(s) the dish actually suits
 - cookingTime: "quick" (under 20 min), "comfort" (30-60 min), "slow" (over an hour or rest time required)
 - benefit: ONE sentence, under 25 words, warm tone
 - time: format like "30 min"
 - ingredients: 6-10 items, each with quantity in parens like "Olive oil (2 tbsp)"
 - simpleSteps: 5-7 conversational sentences. Each step combines actions naturally.
 - cookingMode: 6-12 micro-steps. Each is one atomic action. Include "timer" (number of MINUTES) and "timerLabel" (short, like "Simmer rice") only when the step involves a wait. Most steps do not need a timer.
`;

function validateRecipe(r) {
  const macroVals = ['low', 'medium', 'high'];
  const tasteVals = ['spicy', 'tangy', 'sweet', 'sour', 'balanced'];
  const audVals = ['kids', 'teenagers', 'adults', 'old'];
  const ctVals = ['quick', 'comfort', 'slow'];
  const mtVals = ['breakfast', 'lunch', 'dinner', 'snack'];
  if (!r || typeof r !== 'object') return 'not an object';
  if (typeof r.id !== 'string' || !/^[a-z0-9-]+$/.test(r.id)) return 'bad id';
  if (typeof r.name !== 'string' || r.name.length < 3) return 'bad name';
  if (!r.macros || !macroVals.includes(r.macros.protein) || !macroVals.includes(r.macros.fat) || !macroVals.includes(r.macros.carb)) return 'bad macros';
  if (!tasteVals.includes(r.taste)) return 'bad taste';
  if (!Array.isArray(r.suitableFor) || !r.suitableFor.every(x => audVals.includes(x))) return 'bad suitableFor';
  if (!ctVals.includes(r.cookingTime)) return 'bad cookingTime';
  if (!Array.isArray(r.mealTime) || r.mealTime.length < 1 || !r.mealTime.every(x => mtVals.includes(x))) return 'bad mealTime';
  if (typeof r.benefit !== 'string' || r.benefit.length < 10) return 'bad benefit';
  if (typeof r.time !== 'string') return 'bad time';
  if (!Array.isArray(r.ingredients) || r.ingredients.length < 3) return 'bad ingredients';
  if (!Array.isArray(r.simpleSteps) || r.simpleSteps.length < 3) return 'bad simpleSteps';
  if (!Array.isArray(r.cookingMode) || r.cookingMode.length < 3) return 'bad cookingMode';
  // Defense in depth — reject anything mentioning AI in user-facing text
  const blob = (r.name + ' ' + r.benefit + ' ' + r.simpleSteps.join(' ')).toLowerCase();
  if (/\b(ai|artificial intelligence|chatgpt|claude|llm|gpt|generated by)\b/.test(blob)) return 'forbidden words';
  return null;
}

const recentCalls = new Map();
function rateLimit(key, maxPerHour = 20) {
  const now = Date.now();
  const hour = 60 * 60 * 1000;
  const arr = (recentCalls.get(key) || []).filter(t => now - t < hour);
  if (arr.length >= maxPerHour) return false;
  arr.push(now);
  recentCalls.set(key, arr);
  return true;
}

export default async function handler(req, res) {
  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'POST only' });
  if (process.env.SHARED_SECRET && req.headers['x-app-key'] !== process.env.SHARED_SECRET) {
    return res.status(401).json({ error: 'unauthorized' });
  }
  const ip = req.headers['x-forwarded-for']?.split(',')[0]?.trim() || 'unknown';
  if (!rateLimit(ip)) {
    return res.status(429).json({ error: 'Too many requests. Try again in an hour.' });
  }

  const { prefs, likedRecipes = [], dislikedRecipes = [], avoidNames = [], mealTime = null } = req.body || {};
  if (!prefs?.protein || !prefs?.audience) {
    return res.status(400).json({ error: 'prefs required' });
  }

  const mealLine = mealTime ? `\n- This recipe should suit: ${mealTime}` : '';
  const userMessage = `Family preferences:
- Protein: ${prefs.protein}
- Fat: ${prefs.fat}
- Carb: ${prefs.carb}
- Flavor mood: ${prefs.taste}
- At the table: ${prefs.audience.join(', ')}${prefs.cookingTime ? `\n- Time available: ${prefs.cookingTime}` : ''}${mealLine}

Recipes they have liked: ${likedRecipes.length ? likedRecipes.join(', ') : '(none yet)'}
Recipes they have disliked: ${dislikedRecipes.length ? dislikedRecipes.join(', ') : '(none yet)'}

Avoid suggesting any of these: ${avoidNames.join(', ')}

Suggest ONE new vegetarian recipe in the JSON schema described.`;

  try {
    const response = await anthropic.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 2500,
      system: SYSTEM_PROMPT,
      messages: [{ role: 'user', content: userMessage }],
    });

    const text = response.content.filter(b => b.type === 'text').map(b => b.text).join('').trim();
    const clean = text.replace(/^```json\s*/i, '').replace(/^```\s*/, '').replace(/```\s*$/, '').trim();

    let recipe;
    try { recipe = JSON.parse(clean); }
    catch { return res.status(502).json({ error: 'malformed response' }); }

    const err = validateRecipe(recipe);
    if (err) return res.status(502).json({ error: `validation: ${err}` });

    if (avoidNames.map(n => n.toLowerCase()).includes(recipe.name.toLowerCase())) {
      recipe.id = recipe.id + '-' + Date.now().toString(36);
    }

    res.json(recipe);
  } catch (e) {
    console.error('Backend error:', e);
    res.status(500).json({ error: 'request failed' });
  }
}
