// ============================================================
//  Recipes — seed data + scoring engine
//  Each recipe has simpleSteps, cookingMode, and mealTime tagging
// ============================================================

export const MEAL_TIMES = ['breakfast', 'lunch', 'dinner', 'snack'];

export const MEAL_TIME_LABELS = {
  breakfast: 'Breakfast',
  lunch: 'Lunch',
  dinner: 'Dinner',
  snack: 'Snack',
};

export const MEAL_TIME_LABELS_LUX = {
  breakfast: 'Morning',
  lunch: 'Midday',
  dinner: 'Evening',
  snack: 'Between',
};

export const SEED_RECIPES = [
  {
    id: 'paneer-tikka-bowl', name: 'Paneer Tikka Bowl', accent: '#C2410C',
    macros: { protein: 'high', fat: 'medium', carb: 'medium' }, taste: 'spicy',
    suitableFor: ['adults', 'teenagers'], cookingTime: 'comfort',
    mealTime: ['lunch', 'dinner'],
    benefit: 'Packs 28g of protein per serving — sustained fuel for active days and post-workout recovery.',
    time: '35 min', source: 'seed',
    ingredients: ['Paneer (250g, cubed)', 'Bell peppers (2, chunked)', 'Greek yogurt (1 cup)', 'Garam masala (2 tsp)', 'Brown rice (1 cup, dry)', 'Spinach (2 cups)', 'Lemon (1, juiced)', 'Garlic (4 cloves, minced)'],
    simpleSteps: [
      'Whisk yogurt with garam masala, garlic, and a pinch of salt. Toss the paneer and bell pepper chunks in this marinade for at least 15 minutes.',
      'Start the rice — bring it to a boil with 2 cups water, then simmer covered for 20 minutes.',
      'Heat a wide pan or grill pan over medium-high. Once hot, add the paneer and peppers in a single layer. Cook 8–10 minutes, turning to char the edges.',
      'Wilt the spinach in the same pan with a splash of water — takes about 2 minutes.',
      'Divide the rice into bowls, top with spinach, paneer, and peppers. Squeeze lemon over everything just before eating.',
    ],
    cookingMode: [
      { text: 'Whisk yogurt, garam masala, garlic, and salt in a bowl. Add paneer and bell peppers, toss gently.', timer: 15, timerLabel: 'Marinate' },
      { text: 'Rinse 1 cup brown rice. Combine with 2 cups water in a saucepan. Bring to a boil, then cover and reduce heat to low.', timer: 20, timerLabel: 'Simmer rice' },
      { text: 'Heat a wide pan over medium-high heat. Add the marinated paneer and peppers in a single layer.' },
      { text: 'Cook without stirring for 4 minutes, then flip everything once.', timer: 4, timerLabel: 'First side' },
      { text: 'Cook for another 4 minutes until edges are charred.', timer: 4, timerLabel: 'Second side' },
      { text: 'Push everything to one side of the pan. Add spinach with a splash of water and stir until just wilted.', timer: 2, timerLabel: 'Wilt spinach' },
      { text: 'Divide rice between two bowls. Top with spinach, then paneer and peppers. Finish with lemon juice.' },
    ],
  },
  {
    id: 'chickpea-mediterranean', name: 'Mediterranean Chickpea Stew', accent: '#B45309',
    macros: { protein: 'high', fat: 'medium', carb: 'high' }, taste: 'tangy',
    suitableFor: ['adults', 'old', 'kids'], cookingTime: 'comfort',
    mealTime: ['lunch', 'dinner'],
    benefit: 'Gentle on digestion across ages — fiber and olive oil support heart health for the whole family.',
    time: '40 min', source: 'seed',
    ingredients: ['Chickpeas (2 cans, drained)', 'Tomatoes (4, chopped)', 'Olive oil (3 tbsp)', 'Lemon (2, juiced)', 'Parsley (1 bunch, chopped)', 'Onion (1, diced)', 'Cumin (1 tsp)', 'Pita bread (to serve)'],
    simpleSteps: [
      'Heat olive oil in a large pot over medium heat. Add the diced onion and cook until soft and translucent, about 5 minutes.',
      'Stir in the cumin and let it bloom for 30 seconds — the kitchen will smell like a market.',
      'Add the chopped tomatoes and a generous pinch of salt. Cook down for 10 minutes, stirring occasionally.',
      'Add the drained chickpeas with about half a cup of water. Simmer gently for 15 minutes so the flavors meld.',
      'Finish with lemon juice and chopped parsley. Warm the pita while you ladle into bowls.',
    ],
    cookingMode: [
      { text: 'Heat 3 tbsp olive oil in a large pot over medium heat.' },
      { text: 'Add diced onion and a pinch of salt. Cook until soft and translucent, stirring occasionally.', timer: 5, timerLabel: 'Soften onion' },
      { text: 'Stir in 1 tsp cumin. Let it bloom in the oil for 30 seconds.', timer: 1, timerLabel: 'Bloom spice' },
      { text: 'Add chopped tomatoes and another pinch of salt. Cook down until the tomatoes break apart.', timer: 10, timerLabel: 'Reduce tomatoes' },
      { text: 'Drain the chickpeas and add to the pot with ½ cup water. Stir to combine.' },
      { text: 'Simmer gently, lid slightly ajar, until the flavors meld and stew thickens.', timer: 15, timerLabel: 'Simmer stew' },
      { text: 'Off the heat, squeeze in lemon juice and stir in chopped parsley.' },
      { text: 'Warm pita bread in a dry pan or oven while you serve.', timer: 2, timerLabel: 'Warm pita' },
    ],
  },
  {
    id: 'sweet-potato-pancakes', name: 'Sweet Potato Pancakes', accent: '#DC2626',
    macros: { protein: 'medium', fat: 'low', carb: 'high' }, taste: 'sweet',
    suitableFor: ['kids', 'teenagers', 'adults'], cookingTime: 'quick',
    mealTime: ['breakfast'],
    benefit: 'Naturally sweet so kids skip the syrup — beta-carotene supports growing eyes and immunity.',
    time: '25 min', source: 'seed',
    ingredients: ['Sweet potato (2 large, peeled)', 'Eggs (2)', 'Whole wheat flour (1 cup)', 'Cinnamon (1 tsp)', 'Maple syrup (to serve)', 'Milk (1 cup)', 'Vanilla extract (1 tsp)'],
    simpleSteps: [
      'Cube and microwave the sweet potatoes for 6–8 minutes until completely soft. Mash thoroughly with a fork.',
      'In a large bowl, whisk together the eggs, milk, and vanilla. Add the mashed sweet potato and stir until smooth.',
      'Fold in the flour and cinnamon. The batter should be thick but pourable — add a splash more milk if needed.',
      'Heat a non-stick pan over medium-low. Ladle the batter into rounds. Cook 2–3 minutes per side, until golden.',
      "Stack and serve with maple syrup — though they're sweet enough on their own.",
    ],
    cookingMode: [
      { text: 'Peel and cube 2 large sweet potatoes. Place in a microwave-safe bowl with 2 tbsp water, cover loosely.' },
      { text: 'Microwave on high until completely fork-tender.', timer: 8, timerLabel: 'Cook potato' },
      { text: 'Mash the cooked sweet potato thoroughly with a fork until no lumps remain.' },
      { text: 'In a large bowl, whisk 2 eggs, 1 cup milk, and 1 tsp vanilla extract.' },
      { text: 'Add the mashed sweet potato to the bowl and stir until smooth.' },
      { text: 'Fold in 1 cup whole wheat flour and 1 tsp cinnamon until just combined.' },
      { text: 'Heat a non-stick pan over medium-low heat. Lightly grease.' },
      { text: 'Ladle batter into 4-inch rounds. Cook until bubbles form on top.', timer: 3, timerLabel: 'First side' },
      { text: 'Flip carefully and cook until golden brown.', timer: 2, timerLabel: 'Second side' },
      { text: 'Stack on a warm plate. Serve with maple syrup.' },
    ],
  },
  {
    id: 'thai-tofu-curry', name: 'Thai Red Tofu Curry', accent: '#B91C1C',
    macros: { protein: 'high', fat: 'high', carb: 'medium' }, taste: 'spicy',
    suitableFor: ['adults', 'teenagers'], cookingTime: 'comfort',
    mealTime: ['dinner'],
    benefit: 'Coconut milk delivers MCTs for sustained energy; tofu provides complete plant protein.',
    time: '30 min', source: 'seed',
    ingredients: ['Firm tofu (400g, cubed)', 'Coconut milk (1 can, full-fat)', 'Red curry paste (3 tbsp)', 'Jasmine rice (1 cup, dry)', 'Bok choy (2 heads, halved)', 'Lime (2, juiced)', 'Thai basil (1 handful)', 'Bamboo shoots (1 small can)'],
    simpleSteps: [
      'Rinse the rice and cook it — 1 cup rice with 1.5 cups water, simmered covered for 15 minutes.',
      'Press the tofu between paper towels for 5 minutes to remove excess water, then cube.',
      'In a deep pan, fry the red curry paste in 2 tbsp of the thick top layer of coconut milk for 1–2 minutes until very fragrant.',
      'Pour in the rest of the coconut milk, add the tofu and bamboo shoots, and simmer for 8 minutes.',
      'Add the halved bok choy and cook for another 3 minutes until just tender. Finish with lime juice and torn Thai basil.',
      'Serve over rice in deep bowls — and warn the spice-shy.',
    ],
    cookingMode: [
      { text: 'Rinse 1 cup jasmine rice. Combine with 1.5 cups water in a saucepan and bring to a boil.' },
      { text: 'Reduce heat to low, cover, and cook until water is absorbed.', timer: 15, timerLabel: 'Rice' },
      { text: 'Press 400g firm tofu between paper towels with something heavy on top.', timer: 5, timerLabel: 'Press tofu' },
      { text: 'Cube the pressed tofu into 1-inch pieces.' },
      { text: 'Open the can of coconut milk WITHOUT shaking it. Scoop the thick top cream into a deep pan.' },
      { text: 'Heat the pan over medium. Add 3 tbsp red curry paste and stir constantly until very fragrant and oil separates.', timer: 2, timerLabel: 'Bloom curry' },
      { text: 'Pour in the rest of the coconut milk and stir to combine.' },
      { text: 'Add tofu and drained bamboo shoots. Simmer gently.', timer: 8, timerLabel: 'Infuse tofu' },
      { text: 'Add halved bok choy. Cook until stems are just tender.', timer: 3, timerLabel: 'Tender greens' },
      { text: 'Off the heat: squeeze in lime juice and tear in Thai basil leaves.' },
      { text: 'Fluff the rice with a fork and serve the curry over it in deep bowls.' },
    ],
  },
  {
    id: 'lentil-soup', name: 'Golden Lentil Soup', accent: '#CA8A04',
    macros: { protein: 'medium', fat: 'low', carb: 'medium' }, taste: 'balanced',
    suitableFor: ['old', 'kids', 'adults'], cookingTime: 'comfort',
    mealTime: ['lunch', 'dinner'],
    benefit: 'Soft, easily chewable and iron-rich — well-suited for grandparents and young children alike.',
    time: '30 min', source: 'seed',
    ingredients: ['Red lentils (1 cup, rinsed)', 'Carrots (3, diced)', 'Turmeric (1 tsp)', 'Ginger (1 inch, grated)', 'Vegetable broth (4 cups)', 'Coconut oil (2 tbsp)', 'Cilantro (a handful)', 'Lime (1, juiced)'],
    simpleSteps: [
      'Melt the coconut oil in a pot over medium heat. Add the diced carrots and grated ginger, cook for 4 minutes until fragrant.',
      'Stir in the turmeric — it should turn everything a deep gold. Let it bloom for 30 seconds.',
      'Add the rinsed lentils, broth, and a generous pinch of salt. Bring to a boil, then reduce to a simmer.',
      'Cook for 20 minutes until the lentils completely break down and the soup thickens.',
      'Blend smooth with an immersion blender (or leave rustic). Stir in lime juice and torn cilantro just before serving.',
    ],
    cookingMode: [
      { text: 'Rinse 1 cup red lentils under cold water until the water runs clear.' },
      { text: 'Melt 2 tbsp coconut oil in a heavy pot over medium heat.' },
      { text: 'Add 3 diced carrots and 1 inch grated ginger. Stir occasionally.', timer: 4, timerLabel: 'Soften carrots' },
      { text: 'Stir in 1 tsp turmeric. Cook for 30 seconds until very fragrant.', timer: 1, timerLabel: 'Bloom turmeric' },
      { text: 'Add the rinsed lentils, 4 cups vegetable broth, and 1 tsp salt. Bring to a boil.' },
      { text: 'Reduce heat to low and simmer, partially covered, until lentils completely break down.', timer: 20, timerLabel: 'Simmer soup' },
      { text: 'Off the heat: use an immersion blender to puree until smooth (or leave rustic).' },
      { text: 'Stir in juice of 1 lime and a handful of torn cilantro.' },
    ],
  },
  {
    id: 'quinoa-roasted-veg', name: 'Quinoa & Roasted Vegetable Bowl', accent: '#65A30D',
    macros: { protein: 'medium', fat: 'medium', carb: 'medium' }, taste: 'balanced',
    suitableFor: ['adults', 'teenagers', 'old'], cookingTime: 'comfort',
    mealTime: ['lunch', 'dinner'],
    benefit: 'A complete protein with all nine essential amino acids — balanced fuel without the post-meal slump.',
    time: '35 min', source: 'seed',
    ingredients: ['Quinoa (1 cup, rinsed)', 'Zucchini (2, sliced)', 'Cherry tomatoes (2 cups)', 'Feta cheese (100g, crumbled)', 'Olive oil (3 tbsp)', 'Balsamic vinegar (2 tbsp)', 'Pine nuts (¼ cup)', 'Arugula (2 cups)'],
    simpleSteps: [
      'Preheat the oven to 425°F (220°C). Rinse the quinoa under cold water until it runs clear.',
      'Toss the zucchini and cherry tomatoes with olive oil and salt on a sheet pan. Roast for 20 minutes.',
      'While vegetables roast, simmer the quinoa with 2 cups of water for 15 minutes, then let it rest covered for 5 more.',
      'Toast the pine nuts in a dry pan over medium heat — 3 minutes, shaking often, until golden. Watch closely; they burn fast.',
      'Fluff the quinoa, fold in the arugula, top with the roasted vegetables, crumbled feta, and pine nuts. Drizzle balsamic over.',
    ],
    cookingMode: [
      { text: 'Preheat oven to 425°F (220°C).' },
      { text: 'Rinse 1 cup quinoa in a fine mesh strainer until water runs clear.' },
      { text: 'Slice 2 zucchini into half-moons. Place on a sheet pan with 2 cups cherry tomatoes.' },
      { text: 'Drizzle with 2 tbsp olive oil and a pinch of salt. Toss to coat.' },
      { text: 'Roast in the oven until tomatoes burst and zucchini is tender.', timer: 20, timerLabel: 'Roast vegetables' },
      { text: 'While vegetables roast: combine quinoa and 2 cups water in a saucepan. Bring to a boil.' },
      { text: 'Reduce heat to low, cover, and simmer.', timer: 15, timerLabel: 'Cook quinoa' },
      { text: 'Remove quinoa from heat and let it rest, covered.', timer: 5, timerLabel: 'Rest' },
      { text: 'Toast ¼ cup pine nuts in a dry pan over medium heat, shaking often.', timer: 3, timerLabel: 'Toast pine nuts' },
      { text: 'Fluff quinoa with a fork. Fold in 2 cups arugula.' },
      { text: 'Plate: quinoa base, roasted vegetables, crumbled feta, pine nuts. Drizzle 2 tbsp balsamic over.' },
    ],
  },
  {
    id: 'mango-sticky-rice', name: 'Mango Coconut Sticky Rice', accent: '#D97706',
    macros: { protein: 'low', fat: 'medium', carb: 'high' }, taste: 'sweet',
    suitableFor: ['kids', 'teenagers', 'adults'], cookingTime: 'comfort',
    mealTime: ['snack', 'breakfast'],
    benefit: 'Satisfies the sweet tooth without refined sugar — vitamin C from mango supports immunity.',
    time: '30 min', source: 'seed',
    ingredients: ['Sticky rice (1 cup, soaked)', 'Ripe mango (2, sliced)', 'Coconut milk (1 cup)', 'Palm sugar (¼ cup)', 'Salt (¼ tsp)', 'Sesame seeds (1 tbsp, toasted)'],
    simpleSteps: [
      'Soak the sticky rice for at least 4 hours, or overnight if you can plan ahead.',
      'Drain and steam the rice in a bamboo steamer or fine mesh sieve over boiling water for 25 minutes.',
      'While it steams, gently warm the coconut milk with palm sugar and salt — stir until the sugar dissolves. Do not let it boil.',
      'Pour two-thirds of the coconut sauce over the hot rice, mix gently, and let it absorb for 10 minutes.',
      'Slice the mango thin. Serve mounds of rice with mango on the side, the rest of the coconut sauce poured over, and a sprinkle of sesame.',
    ],
    cookingMode: [
      { text: 'Place 1 cup sticky rice in a bowl, cover with water, and soak.', timer: 240, timerLabel: 'Soak rice' },
      { text: 'Drain the rice thoroughly.' },
      { text: 'Set up a bamboo steamer or fine mesh sieve over a pot of boiling water. Place rice inside.' },
      { text: 'Steam covered until rice is translucent and tender.', timer: 25, timerLabel: 'Steam rice' },
      { text: 'In a small saucepan, gently warm 1 cup coconut milk, ¼ cup palm sugar, and ¼ tsp salt.' },
      { text: 'Stir until the sugar dissolves completely. Do not boil.', timer: 3, timerLabel: 'Make sauce' },
      { text: 'Transfer hot rice to a bowl. Pour ⅔ of the warm coconut sauce over it.' },
      { text: 'Gently mix and let the rice absorb the sauce.', timer: 10, timerLabel: 'Absorb' },
      { text: 'Slice 2 ripe mangoes into thin slabs.' },
      { text: 'Mound rice on plates, fan mango slices alongside. Drizzle remaining sauce. Sprinkle sesame seeds over.' },
    ],
  },
  {
    id: 'tamarind-rasam', name: 'Tangy Tomato Rasam', accent: '#BE123C',
    macros: { protein: 'low', fat: 'low', carb: 'low' }, taste: 'sour',
    suitableFor: ['old', 'adults'], cookingTime: 'quick',
    mealTime: ['lunch', 'dinner'],
    benefit: 'Tamarind aids digestion; light and warming, gentle on senior stomachs.',
    time: '20 min', source: 'seed',
    ingredients: ['Tomatoes (4, chopped)', 'Tamarind paste (2 tbsp)', 'Toor dal (½ cup, rinsed)', 'Curry leaves (10)', 'Mustard seeds (1 tsp)', 'Asafoetida (pinch)', 'Black pepper (½ tsp, freshly ground)', 'Cilantro (a handful, chopped)'],
    simpleSteps: [
      'Cook the toor dal: pressure cook for 3 whistles with 2 cups water, or simmer for 25 minutes until mushy.',
      'In a separate pot, simmer the chopped tomatoes with tamarind paste, black pepper, and 3 cups of water for 8 minutes.',
      'Mash the cooked dal and add it to the rasam pot. Simmer gently for 5 more minutes — do not let it boil hard.',
      'In a tiny pan, heat 1 tsp oil and pop the mustard seeds. Add curry leaves and asafoetida — they will sizzle and crackle.',
      'Pour this tempering over the rasam, add chopped cilantro, and serve hot in small bowls or as a soup.',
    ],
    cookingMode: [
      { text: 'Rinse ½ cup toor dal. Add to a pressure cooker with 2 cups water.' },
      { text: 'Pressure cook for 3 whistles, then let pressure release naturally.', timer: 20, timerLabel: 'Cook dal' },
      { text: 'While dal cooks: chop 4 tomatoes and place in a separate pot.' },
      { text: 'Add 2 tbsp tamarind paste, ½ tsp pepper, and 3 cups water. Bring to a gentle simmer.' },
      { text: 'Simmer until tomatoes soften and the broth turns rust-orange.', timer: 8, timerLabel: 'Tomato broth' },
      { text: 'Mash the cooked dal until smooth. Add it to the rasam pot and stir.' },
      { text: 'Simmer very gently — do not boil hard or it goes cloudy.', timer: 5, timerLabel: 'Marry flavors' },
      { text: 'In a small tadka pan, heat 1 tsp oil over medium-high.' },
      { text: 'Add 1 tsp mustard seeds. When they pop, add 10 curry leaves and a pinch of asafoetida.', timer: 1, timerLabel: 'Temper' },
      { text: 'Pour the sizzling tempering over the rasam. Stir in chopped cilantro.' },
      { text: 'Serve hot in small bowls.' },
    ],
  },
  {
    id: 'avocado-toast-deluxe', name: 'Avocado Toast with Egg', accent: '#15803D',
    macros: { protein: 'medium', fat: 'high', carb: 'medium' }, taste: 'balanced',
    suitableFor: ['adults', 'teenagers'], cookingTime: 'quick',
    mealTime: ['breakfast', 'lunch'],
    benefit: 'Healthy fats from avocado support brain function — keeps teenagers focused through morning classes.',
    time: '15 min', source: 'seed',
    ingredients: ['Avocado (2, ripe)', 'Sourdough bread (4 slices)', 'Eggs (4)', 'Chili flakes (to taste)', 'Lemon (1, juiced)', 'Sea salt (flaky)', 'Microgreens (a small handful)'],
    simpleSteps: [
      'Toast the sourdough until deeply golden — really golden, not pale. This is the foundation.',
      'While the bread toasts, halve and pit the avocados. Scoop into a bowl with a generous squeeze of lemon and a pinch of salt. Mash to your preferred texture.',
      'In a non-stick pan over medium heat, cook the eggs sunny-side-up in a film of olive oil — about 3 minutes for runny yolks.',
      'Spread the avocado generously on the toast. Slide an egg on top of each.',
      'Finish with flaky salt, chili flakes, and a few microgreens. Crack pepper if you like.',
    ],
    cookingMode: [
      { text: 'Toast 4 slices of sourdough bread until deeply golden — not pale.', timer: 3, timerLabel: 'Toast bread' },
      { text: 'Halve and pit 2 ripe avocados. Scoop into a bowl.' },
      { text: 'Add juice of 1 lemon and a generous pinch of salt. Mash with a fork to your preferred texture.' },
      { text: 'Heat a non-stick pan over medium heat. Add 1 tsp olive oil.' },
      { text: 'Crack in 4 eggs, leaving space between them. Cook undisturbed.', timer: 3, timerLabel: 'Sunny eggs' },
      { text: 'Spread the mashed avocado generously over each piece of toast.' },
      { text: 'Slide an egg on top of each toast.' },
      { text: 'Finish with flaky sea salt, chili flakes, and microgreens.' },
    ],
  },
  {
    id: 'spinach-paneer-paratha', name: 'Spinach Paneer Paratha', accent: '#166534',
    macros: { protein: 'high', fat: 'medium', carb: 'high' }, taste: 'balanced',
    suitableFor: ['kids', 'teenagers', 'adults', 'old'], cookingTime: 'slow',
    mealTime: ['breakfast', 'lunch', 'dinner'],
    benefit: 'Iron-rich spinach folded inside flatbread — kids eat their greens without protest.',
    time: '40 min', source: 'seed',
    ingredients: ['Whole wheat flour (2 cups)', 'Paneer (200g, grated)', 'Spinach (3 cups, finely chopped)', 'Ginger (1 inch, grated)', 'Green chili (1, minced)', 'Cumin (1 tsp)', 'Ghee (for cooking)', 'Yogurt (to serve)'],
    simpleSteps: [
      'Make the dough: mix flour with ¾ cup water and a pinch of salt. Knead for 5 minutes until smooth. Cover and rest for 15 minutes.',
      'Wilt the chopped spinach in a dry pan for 2 minutes, then squeeze out as much water as you can — this is the key step.',
      'Mix the squeezed spinach, grated paneer, ginger, chili, cumin, and salt in a bowl. The filling should be barely moist.',
      'Divide dough into 6 balls. Roll each into a small disc, place a heaping spoonful of filling in the center, pinch to seal, then roll out gently to flatten.',
      'Cook on a hot tawa or skillet, 2 minutes per side, brushing with ghee. Serve hot with cool yogurt.',
    ],
    cookingMode: [
      { text: 'In a large bowl, combine 2 cups whole wheat flour, ½ tsp salt, and ¾ cup water.' },
      { text: 'Knead with your hands until smooth and elastic.', timer: 5, timerLabel: 'Knead' },
      { text: 'Cover with a damp cloth and let rest.', timer: 15, timerLabel: 'Rest dough' },
      { text: 'While dough rests: finely chop 3 cups spinach.' },
      { text: 'Wilt the spinach in a dry pan over medium heat.', timer: 2, timerLabel: 'Wilt' },
      { text: 'Transfer wilted spinach to a clean towel. Squeeze out as much water as possible — be ruthless.' },
      { text: 'In a bowl, combine the squeezed spinach, 200g grated paneer, grated ginger, minced chili, 1 tsp cumin, and salt.' },
      { text: 'Divide rested dough into 6 equal balls.' },
      { text: 'Take one ball. Flatten into a 4-inch disc with your hands.' },
      { text: 'Place a heaping spoonful of filling in the center. Gather edges up and pinch closed at the top.' },
      { text: "Flatten gently and roll out into a 7-inch round, dusting with flour as needed. Don't rush — patches will tear." },
      { text: 'Heat a tawa or skillet over medium-high heat.' },
      { text: 'Cook each paratha 2 minutes per side, brushing with ghee, until golden brown spots form.', timer: 4, timerLabel: 'Cook paratha' },
      { text: 'Repeat with remaining dough and filling. Serve hot with yogurt.' },
    ],
  },
  {
    id: 'kimchi-fried-rice', name: 'Kimchi Fried Rice', accent: '#9F1239',
    macros: { protein: 'medium', fat: 'medium', carb: 'high' }, taste: 'tangy',
    suitableFor: ['adults', 'teenagers'], cookingTime: 'quick',
    mealTime: ['lunch', 'dinner'],
    benefit: 'Fermented kimchi supports gut health — probiotics improve immunity and digestion.',
    time: '20 min', source: 'seed',
    ingredients: ['Cooked rice (3 cups, day-old)', 'Kimchi (1 cup, chopped)', 'Eggs (2)', 'Scallions (4, sliced)', 'Sesame oil (2 tbsp)', 'Soy sauce (1 tbsp)', 'Gochujang (1 tbsp)', 'Nori (2 sheets, torn)'],
    simpleSteps: [
      'Day-old rice is non-negotiable. Fresh rice goes mushy. If you must use fresh, spread it on a sheet pan to cool first.',
      'Heat sesame oil in a wide pan over medium-high. Add the kimchi and stir-fry for 3 minutes until the edges caramelize.',
      'Stir in the gochujang for 30 seconds, then add the rice. Press it against the pan to develop crispy bits — leave it alone for stretches.',
      'Push the rice to one side, crack the eggs into the empty side, scramble them, then fold everything together.',
      'Finish with soy sauce, scallions, and torn nori. Eat directly from the pan.',
    ],
    cookingMode: [
      { text: 'Have 3 cups of day-old cooked rice ready. If freshly cooked, spread on a sheet pan to cool first.' },
      { text: 'Chop 1 cup kimchi. Slice 4 scallions.' },
      { text: 'Heat 2 tbsp sesame oil in a wide pan over medium-high heat.' },
      { text: 'Add the chopped kimchi. Stir-fry until edges caramelize.', timer: 3, timerLabel: 'Caramelize kimchi' },
      { text: 'Stir in 1 tbsp gochujang. Cook for 30 seconds until fragrant.', timer: 1, timerLabel: 'Bloom paste' },
      { text: 'Add the cold rice. Press it down against the pan to create a thin layer.' },
      { text: 'Cook undisturbed to develop crispy bits.', timer: 2, timerLabel: 'Crisp rice' },
      { text: 'Stir, then press flat again. Cook for another 2 minutes.', timer: 2, timerLabel: 'Crisp more' },
      { text: 'Push rice to one side of the pan. Crack 2 eggs into the empty side and scramble.', timer: 1, timerLabel: 'Eggs' },
      { text: 'Fold everything together. Drizzle 1 tbsp soy sauce around the edges.' },
      { text: 'Off the heat: scatter sliced scallions and torn nori sheets. Serve immediately.' },
    ],
  },
  {
    id: 'oatmeal-berry-bowl', name: 'Cinnamon Berry Oatmeal', accent: '#7C3AED',
    macros: { protein: 'low', fat: 'low', carb: 'high' }, taste: 'sweet',
    suitableFor: ['kids', 'old', 'adults'], cookingTime: 'quick',
    mealTime: ['breakfast'],
    benefit: 'Beta-glucan in oats lowers cholesterol — a gentle morning bowl that suits every generation.',
    time: '15 min', source: 'seed',
    ingredients: ['Rolled oats (1 cup)', 'Mixed berries (2 cups, fresh or frozen)', 'Milk (2 cups)', 'Cinnamon (½ tsp)', 'Honey (to drizzle)', 'Almonds (¼ cup, sliced)', 'Chia seeds (1 tbsp)'],
    simpleSteps: [
      'In a saucepan, bring the milk just to a simmer over medium heat — watch it, milk burns fast.',
      'Add the oats, cinnamon, and a pinch of salt. Stir, lower the heat, and simmer for 7 minutes, stirring occasionally.',
      'Meanwhile, if using frozen berries, warm them in a small pan with a splash of water for 3 minutes until juicy.',
      'Stir the chia seeds into the cooked oats — they thicken everything in a minute or two.',
      'Ladle into bowls, top with warm berries, sliced almonds, and a thread of honey.',
    ],
    cookingMode: [
      { text: 'Pour 2 cups milk into a saucepan. Heat over medium until just simmering.', timer: 3, timerLabel: 'Heat milk' },
      { text: 'Add 1 cup rolled oats, ½ tsp cinnamon, and a pinch of salt. Stir.' },
      { text: 'Reduce heat to medium-low and simmer, stirring occasionally.', timer: 7, timerLabel: 'Cook oats' },
      { text: 'In a small pan, warm 2 cups berries with a splash of water until juicy.', timer: 3, timerLabel: 'Warm berries' },
      { text: 'When oats are done, stir in 1 tbsp chia seeds. Let them thicken.', timer: 1, timerLabel: 'Thicken' },
      { text: 'Divide oatmeal into bowls. Top with warm berries.' },
      { text: 'Sprinkle ¼ cup sliced almonds over. Finish with a thread of honey.' },
    ],
  },
  {
    id: 'cauliflower-rice-pulao', name: 'Cauliflower Rice Pulao', accent: '#84CC16',
    macros: { protein: 'medium', fat: 'medium', carb: 'low' }, taste: 'spicy',
    suitableFor: ['adults', 'teenagers', 'old', 'kids'], cookingTime: 'quick',
    mealTime: ['lunch', 'dinner'],
    benefit: 'All the warmth of pulao with a fraction of the carbs — cauliflower stands in for rice, spices do the rest.',
    time: '20 min', source: 'seed',
    ingredients: ['Cauliflower (1 head, riced)', 'Peas (1 cup, frozen)', 'Carrots (2, diced)', 'Cumin seeds (1 tsp)', 'Garam masala (1 tsp)', 'Turmeric (½ tsp)', 'Ghee (2 tbsp)', 'Cashews (¼ cup)'],
    simpleSteps: [
      'Cut the cauliflower into florets and pulse in a food processor until it looks like rice. Don\'t over-process or you\'ll get mush.',
      'Heat ghee in a wide pan over medium-high. Add cumin seeds and let them sizzle for 30 seconds.',
      'Add carrots and cook for 3 minutes until they start to soften. Toss in the cashews and let them turn golden.',
      'Stir in turmeric and garam masala, then add the cauliflower rice and peas. Cook 5–7 minutes, stirring occasionally.',
      'The cauliflower should be tender but still have a slight bite. Salt to taste and serve hot.',
    ],
    cookingMode: [
      { text: 'Cut 1 head of cauliflower into florets. Pulse in a food processor until rice-sized — about 8 short pulses.' },
      { text: 'Heat 2 tbsp ghee in a wide pan over medium-high heat.' },
      { text: 'Add 1 tsp cumin seeds. Wait until they sizzle and pop.', timer: 1, timerLabel: 'Bloom cumin' },
      { text: 'Add 2 diced carrots. Cook, stirring occasionally.', timer: 3, timerLabel: 'Soften carrots' },
      { text: 'Add ¼ cup cashews and toast until golden.', timer: 2, timerLabel: 'Toast cashews' },
      { text: 'Stir in ½ tsp turmeric and 1 tsp garam masala. Let bloom in the oil.', timer: 1, timerLabel: 'Bloom spices' },
      { text: 'Add the cauliflower rice and 1 cup frozen peas. Stir to coat.' },
      { text: 'Cook, stirring occasionally, until cauliflower is tender but not mushy.', timer: 6, timerLabel: 'Cook pulao' },
      { text: 'Salt to taste. Serve hot.' },
    ],
  },
  {
    id: 'greek-halloumi-salad', name: 'Greek Salad with Halloumi', accent: '#0E7490',
    macros: { protein: 'high', fat: 'high', carb: 'low' }, taste: 'tangy',
    suitableFor: ['adults', 'teenagers'], cookingTime: 'quick',
    mealTime: ['lunch', 'dinner'],
    benefit: 'High-protein cheese, briny olives, crisp vegetables — Mediterranean satisfaction without bread or grain.',
    time: '15 min', source: 'seed',
    ingredients: ['Halloumi cheese (250g, sliced)', 'Cucumber (1 large, chunked)', 'Cherry tomatoes (2 cups)', 'Red onion (½, thinly sliced)', 'Kalamata olives (½ cup)', 'Olive oil (3 tbsp)', 'Red wine vinegar (1 tbsp)', 'Oregano (1 tsp, dried)'],
    simpleSteps: [
      'Slice the halloumi into ½-inch slabs. Pat dry with paper towels — wet halloumi spatters dangerously in the pan.',
      'Heat a dry pan over medium-high. Sear the halloumi 2 minutes per side until golden brown crust forms. No oil needed.',
      'While it sears, chunk the cucumber and halve the tomatoes. Slice the red onion very thin.',
      'Toss the vegetables with olives, olive oil, vinegar, oregano, and a pinch of salt and pepper.',
      'Plate the salad, top with hot halloumi slices, and eat immediately while the cheese still has its crust.',
    ],
    cookingMode: [
      { text: 'Slice 250g halloumi into ½-inch slabs. Pat dry thoroughly with paper towels.' },
      { text: 'Chunk 1 cucumber and halve 2 cups cherry tomatoes.' },
      { text: 'Slice ½ red onion very thinly.' },
      { text: 'In a bowl, combine the vegetables with ½ cup kalamata olives.' },
      { text: 'Add 3 tbsp olive oil, 1 tbsp red wine vinegar, 1 tsp oregano. Toss with a pinch of salt and pepper.' },
      { text: 'Heat a dry pan over medium-high heat.' },
      { text: 'Add halloumi slices. Sear undisturbed until golden brown.', timer: 2, timerLabel: 'First side' },
      { text: 'Flip and sear the other side.', timer: 2, timerLabel: 'Second side' },
      { text: 'Plate the salad. Top with hot halloumi. Serve immediately.' },
    ],
  },
  {
    id: 'paneer-bhurji', name: 'Spinach Paneer Bhurji', accent: '#16A34A',
    macros: { protein: 'high', fat: 'medium', carb: 'low' }, taste: 'spicy',
    suitableFor: ['adults', 'teenagers', 'old'], cookingTime: 'quick',
    mealTime: ['breakfast', 'lunch', 'dinner'],
    benefit: 'Scrambled paneer with spinach — 25g of complete protein, ready in under 15 minutes, no bread required.',
    time: '15 min', source: 'seed',
    ingredients: ['Paneer (300g, crumbled)', 'Spinach (3 cups, chopped)', 'Tomato (1 large, diced)', 'Onion (1 medium, finely diced)', 'Green chili (1, minced)', 'Ginger-garlic paste (1 tbsp)', 'Turmeric (½ tsp)', 'Ghee (1 tbsp)'],
    simpleSteps: [
      'Crumble the paneer between your hands until it looks like coarse cottage cheese.',
      'Heat ghee in a wide pan over medium. Add onion and green chili. Cook for 4 minutes until softened.',
      'Add ginger-garlic paste and turmeric. Cook 1 minute. Add diced tomato and cook until it breaks down, about 3 minutes.',
      'Stir in the chopped spinach and let it wilt completely — about 2 minutes.',
      'Add the crumbled paneer, season with salt, and stir gently for 2 minutes until everything is heated through. Eat with a fork.',
    ],
    cookingMode: [
      { text: 'Crumble 300g paneer with your hands into a coarse cottage-cheese texture.' },
      { text: 'Finely dice 1 onion and 1 tomato. Mince 1 green chili. Chop 3 cups spinach.' },
      { text: 'Heat 1 tbsp ghee in a wide pan over medium heat.' },
      { text: 'Add diced onion and minced chili. Cook until softened.', timer: 4, timerLabel: 'Soften onion' },
      { text: 'Add 1 tbsp ginger-garlic paste and ½ tsp turmeric. Cook for 1 minute.', timer: 1, timerLabel: 'Bloom spices' },
      { text: 'Add diced tomato. Cook until it breaks down into a paste.', timer: 3, timerLabel: 'Cook tomato' },
      { text: 'Add chopped spinach. Stir until completely wilted.', timer: 2, timerLabel: 'Wilt spinach' },
      { text: 'Add the crumbled paneer and a generous pinch of salt. Stir gently to combine.' },
      { text: 'Cook for 2 minutes until everything is heated through.', timer: 2, timerLabel: 'Warm through' },
    ],
  },
  {
    id: 'zucchini-noodles-pesto', name: 'Zucchini Noodles with Pesto', accent: '#15803D',
    macros: { protein: 'medium', fat: 'high', carb: 'low' }, taste: 'balanced',
    suitableFor: ['adults', 'teenagers'], cookingTime: 'quick',
    mealTime: ['lunch', 'dinner'],
    benefit: 'All the comfort of pasta, none of the heaviness — basil pesto and pine nuts deliver real flavor.',
    time: '15 min', source: 'seed',
    ingredients: ['Zucchini (3 large)', 'Fresh basil (2 cups, packed)', 'Pine nuts (⅓ cup)', 'Parmesan (½ cup, grated)', 'Garlic (2 cloves)', 'Olive oil (½ cup)', 'Cherry tomatoes (1 cup, halved)', 'Lemon (1, juiced)'],
    simpleSteps: [
      'Spiralize the zucchini, or use a vegetable peeler to make ribbons. Salt the noodles lightly and let sit in a colander for 10 minutes — this draws out water.',
      'While they drain, make the pesto. Blend basil, pine nuts (reserve a few for garnish), parmesan, garlic, and olive oil into a smooth paste. Season with salt and lemon juice.',
      'Press the zucchini noodles in a clean towel to squeeze out the released water. Skipping this makes everything soggy.',
      'In a wide pan over medium heat, briefly warm the noodles for 1 minute. Do not actually cook them — you want them tender-crisp.',
      'Off the heat, toss with as much pesto as you like and the cherry tomatoes. Top with reserved pine nuts.',
    ],
    cookingMode: [
      { text: 'Spiralize 3 large zucchini into noodles, or use a peeler to make ribbons.' },
      { text: 'Toss the noodles with 1 tsp salt and place in a colander to drain.', timer: 10, timerLabel: 'Draw out water' },
      { text: 'In a food processor, combine 2 cups basil, ⅓ cup pine nuts (save 1 tbsp for garnish), ½ cup parmesan, and 2 garlic cloves.' },
      { text: 'Pulse a few times, then stream in ½ cup olive oil while running. Blend until smooth.' },
      { text: 'Stir in juice of 1 lemon and salt to taste.' },
      { text: 'After 10 minutes, transfer drained zucchini to a clean towel. Twist and squeeze firmly to remove water.' },
      { text: 'Heat a wide pan over medium heat — no oil. Add the squeezed noodles.' },
      { text: 'Warm gently, tossing constantly. They should stay tender-crisp.', timer: 1, timerLabel: 'Warm noodles' },
      { text: 'Off the heat, toss with pesto to taste and 1 cup halved cherry tomatoes.' },
      { text: 'Plate and sprinkle reserved pine nuts on top.' },
    ],
  },
  {
    id: 'masala-egg-bhurji', name: 'Masala Egg Bhurji', accent: '#EA580C',
    macros: { protein: 'high', fat: 'medium', carb: 'low' }, taste: 'spicy',
    suitableFor: ['adults', 'teenagers', 'kids', 'old'], cookingTime: 'quick',
    mealTime: ['breakfast', 'lunch', 'dinner'],
    benefit: 'Spiced Indian scrambled eggs — fast, satisfying, and gentle enough for everyone at the table.',
    time: '12 min', source: 'seed',
    ingredients: ['Eggs (6)', 'Onion (1 medium, finely diced)', 'Tomato (1 large, diced)', 'Green chili (1, minced — optional)', 'Cumin seeds (½ tsp)', 'Turmeric (¼ tsp)', 'Ghee (1 tbsp)', 'Cilantro (a handful, chopped)'],
    simpleSteps: [
      'Heat ghee in a wide pan over medium heat. Add cumin seeds and wait for the sizzle — about 30 seconds.',
      'Add diced onion (and green chili if using). Cook for 3 minutes until soft and translucent.',
      'Stir in turmeric, then add diced tomato. Cook for 2 minutes until the tomato breaks down.',
      'Crack the eggs directly into the pan, salt them, and stir continuously. Soft curds form in about 90 seconds — pull them off the heat before they look done; they keep cooking.',
      'Stir in chopped cilantro. Eat with a fork, or roll up in lettuce leaves for crunch.',
    ],
    cookingMode: [
      { text: 'Finely dice 1 onion and 1 tomato. Mince 1 green chili if using.' },
      { text: 'Heat 1 tbsp ghee in a wide pan over medium heat.' },
      { text: 'Add ½ tsp cumin seeds. Wait for the sizzle.', timer: 1, timerLabel: 'Bloom cumin' },
      { text: 'Add diced onion and chili. Cook until soft and translucent.', timer: 3, timerLabel: 'Soften onion' },
      { text: 'Stir in ¼ tsp turmeric. Add diced tomato.' },
      { text: 'Cook until tomato breaks down into a paste.', timer: 2, timerLabel: 'Cook tomato' },
      { text: 'Crack 6 eggs directly into the pan. Add a generous pinch of salt.' },
      { text: 'Stir continuously with a spatula. Eggs will form soft curds.', timer: 2, timerLabel: 'Scramble' },
      { text: 'Pull off the heat while they still look slightly underdone — they keep cooking.' },
      { text: 'Stir in chopped cilantro. Serve immediately.' },
    ],
  },
  {
    id: 'stuffed-peppers-paneer', name: 'Paneer-Stuffed Bell Peppers', accent: '#DC2626',
    macros: { protein: 'high', fat: 'medium', carb: 'low' }, taste: 'balanced',
    suitableFor: ['adults', 'teenagers', 'kids'], cookingTime: 'comfort',
    mealTime: ['lunch', 'dinner'],
    benefit: 'Whole bell peppers cradle a savory paneer and herb filling — looks impressive, takes one pan.',
    time: '40 min', source: 'seed',
    ingredients: ['Bell peppers (4 large, mixed colors)', 'Paneer (300g, crumbled)', 'Mozzarella (½ cup, shredded)', 'Almonds (¼ cup, chopped)', 'Spinach (2 cups, chopped)', 'Garlic (3 cloves, minced)', 'Italian herbs (1 tbsp)', 'Olive oil (2 tbsp)'],
    simpleSteps: [
      'Preheat the oven to 400°F (200°C). Slice the tops off the bell peppers and scoop out the seeds. Keep the tops as little lids.',
      'In a pan, heat olive oil and cook the garlic for 30 seconds. Add chopped spinach and wilt for 2 minutes.',
      'Off the heat, mix in the crumbled paneer, half the mozzarella, almonds, Italian herbs, and salt to taste.',
      'Stuff each pepper full with the mixture, pressing down gently. Sprinkle remaining mozzarella on top.',
      'Place stuffed peppers in a baking dish, replace their tops, and bake for 30 minutes. The peppers should be tender and the cheese golden.',
    ],
    cookingMode: [
      { text: 'Preheat oven to 400°F (200°C).' },
      { text: 'Slice the tops off 4 large bell peppers. Scoop out and discard the seeds.' },
      { text: 'Set the pepper tops aside — they\'ll serve as lids.' },
      { text: 'Heat 2 tbsp olive oil in a pan over medium heat. Add 3 minced garlic cloves.' },
      { text: 'Cook garlic until fragrant but not browned.', timer: 1, timerLabel: 'Bloom garlic' },
      { text: 'Add 2 cups chopped spinach. Wilt completely.', timer: 2, timerLabel: 'Wilt spinach' },
      { text: 'Remove pan from heat. Stir in 300g crumbled paneer, ¼ cup mozzarella, ¼ cup chopped almonds, 1 tbsp Italian herbs.' },
      { text: 'Season the mixture generously with salt and pepper.' },
      { text: 'Stuff each pepper full with the mixture, pressing down gently.' },
      { text: 'Top each pepper with the remaining ¼ cup mozzarella.' },
      { text: 'Place in a baking dish. Cover each with its reserved top.' },
      { text: 'Bake until peppers are tender and cheese is golden.', timer: 30, timerLabel: 'Bake' },
    ],
  },
  {
    id: 'mushroom-paneer-stirfry', name: 'Mushroom & Paneer Stir-fry', accent: '#7C2D12',
    macros: { protein: 'high', fat: 'medium', carb: 'low' }, taste: 'tangy',
    suitableFor: ['adults', 'teenagers'], cookingTime: 'quick',
    mealTime: ['lunch', 'dinner'],
    benefit: 'Indo-Chinese stir-fry without rice — meaty mushrooms and golden paneer in a tangy soy-chili glaze.',
    time: '20 min', source: 'seed',
    ingredients: ['Paneer (300g, cubed)', 'Mushrooms (400g, sliced)', 'Bell pepper (1, julienned)', 'Spring onions (4, sliced)', 'Garlic (4 cloves, minced)', 'Soy sauce (2 tbsp)', 'Chili sauce (1 tbsp)', 'Sesame oil (2 tbsp)'],
    simpleSteps: [
      'Heat 1 tbsp sesame oil in a wide pan or wok over high heat. Add paneer cubes and pan-fry until golden on all sides — about 4 minutes total. Remove and set aside.',
      'In the same pan, add the rest of the oil. Toss in garlic and the white parts of the spring onions. Cook 30 seconds.',
      'Add sliced mushrooms in a single layer. Don\'t stir for 2 minutes — let them get a golden sear, then stir.',
      'Add bell pepper and stir-fry for 2 more minutes. Return paneer to the pan.',
      'Pour in soy sauce and chili sauce. Toss everything together for 1 minute. Scatter spring onion greens on top and serve immediately.',
    ],
    cookingMode: [
      { text: 'Cube 300g paneer into 1-inch pieces. Slice 400g mushrooms. Julienne 1 bell pepper. Slice 4 spring onions, separating whites from greens.' },
      { text: 'Heat 1 tbsp sesame oil in a wok or wide pan over high heat.' },
      { text: 'Add paneer cubes in a single layer. Pan-fry until golden on multiple sides.', timer: 4, timerLabel: 'Brown paneer' },
      { text: 'Remove paneer to a plate. Set aside.' },
      { text: 'Add remaining 1 tbsp sesame oil. Add 4 minced garlic cloves and spring onion whites.' },
      { text: 'Stir-fry for 30 seconds until fragrant.', timer: 1, timerLabel: 'Aromatics' },
      { text: 'Add sliced mushrooms in a single layer. Do not stir.', timer: 2, timerLabel: 'Sear mushrooms' },
      { text: 'Stir, then add julienned bell pepper. Stir-fry.', timer: 2, timerLabel: 'Pepper' },
      { text: 'Return paneer to the pan. Add 2 tbsp soy sauce and 1 tbsp chili sauce.' },
      { text: 'Toss everything to coat.', timer: 1, timerLabel: 'Glaze' },
      { text: 'Scatter spring onion greens on top. Serve immediately.' },
    ],
  },
  {
    id: 'avocado-cucumber-feta', name: 'Avocado Cucumber Salad with Feta', accent: '#10B981',
    macros: { protein: 'medium', fat: 'high', carb: 'low' }, taste: 'tangy',
    suitableFor: ['adults', 'teenagers', 'old'], cookingTime: 'quick',
    mealTime: ['breakfast', 'lunch', 'snack'],
    benefit: 'Five minutes, no cooking, healthy fats from avocado and protein from feta — perfect summer lunch.',
    time: '10 min', source: 'seed',
    ingredients: ['Avocado (2, ripe)', 'Cucumber (1 large, diced)', 'Feta cheese (150g, crumbled)', 'Cherry tomatoes (1 cup, halved)', 'Red onion (¼, finely diced)', 'Olive oil (2 tbsp)', 'Lemon (1, juiced)', 'Fresh mint (small handful, chopped)'],
    simpleSteps: [
      'Halve, pit, and dice the avocados into ½-inch cubes.',
      'In a bowl, gently combine the avocado, diced cucumber, halved cherry tomatoes, and finely diced red onion.',
      'Whisk olive oil with lemon juice, a generous pinch of salt, and freshly cracked pepper.',
      'Pour the dressing over the salad and toss carefully — avocado breaks easily.',
      'Crumble feta on top and scatter with chopped mint. Eat immediately so the avocado stays green.',
    ],
    cookingMode: [
      { text: 'Halve and pit 2 ripe avocados. Dice into ½-inch cubes.' },
      { text: 'Dice 1 cucumber and halve 1 cup cherry tomatoes.' },
      { text: 'Finely dice ¼ red onion.' },
      { text: 'In a large bowl, gently combine all the vegetables and avocado.' },
      { text: 'In a small bowl, whisk 2 tbsp olive oil, juice of 1 lemon, salt, and pepper.' },
      { text: 'Pour the dressing over the salad. Toss very gently — avocado breaks easily.' },
      { text: 'Crumble 150g feta on top.' },
      { text: 'Scatter chopped mint over. Serve immediately.' },
    ],
  },
  {
    id: 'yellow-dal-tadka', name: 'Yellow Dal Tadka', accent: '#EAB308',
    macros: { protein: 'medium', fat: 'low', carb: 'low' }, taste: 'spicy',
    suitableFor: ['adults', 'teenagers', 'old', 'kids'], cookingTime: 'comfort',
    mealTime: ['lunch', 'dinner'],
    benefit: 'Soft yellow lentils crowned with sizzling spices — lean comfort food that suits every age.',
    time: '30 min', source: 'seed',
    ingredients: ['Toor dal (1 cup, rinsed)', 'Turmeric (1 tsp)', 'Tomato (1, diced)', 'Garlic (4 cloves, sliced)', 'Cumin seeds (1 tsp)', 'Dried red chilies (2)', 'Ghee (1 tbsp)', 'Cilantro (a handful, chopped)'],
    simpleSteps: [
      'Rinse the toor dal until the water runs clear. Combine with 3 cups water, turmeric, and a pinch of salt in a pot.',
      'Bring to a boil, then reduce heat. Simmer for 20 minutes until the dal is completely soft. Mash with the back of a spoon.',
      'Stir in the diced tomato and cook for 5 more minutes. Add water if it gets too thick.',
      'In a small pan, heat ghee. Add cumin seeds, sliced garlic, and dried chilies. Let them sizzle until garlic turns golden — about 1 minute.',
      'Pour the sizzling tempering over the dal. Stir, top with chopped cilantro, and serve.',
    ],
    cookingMode: [
      { text: 'Rinse 1 cup toor dal under cold water until water runs clear.' },
      { text: 'In a pot, combine the dal with 3 cups water, 1 tsp turmeric, and a pinch of salt.' },
      { text: 'Bring to a boil, then reduce heat to low. Simmer partially covered.', timer: 20, timerLabel: 'Cook dal' },
      { text: 'When dal is soft, mash gently with the back of a spoon to break it down.' },
      { text: 'Stir in 1 diced tomato. Continue simmering.', timer: 5, timerLabel: 'Cook tomato' },
      { text: 'In a small tadka pan, heat 1 tbsp ghee over medium-high heat.' },
      { text: 'Add 1 tsp cumin seeds, 4 sliced garlic cloves, and 2 dried red chilies.' },
      { text: 'Sizzle until garlic turns golden brown.', timer: 1, timerLabel: 'Tadka' },
      { text: 'Pour the sizzling tempering over the dal. Stir.' },
      { text: 'Top with chopped cilantro. Serve hot.' },
    ],
  },
  {
    id: 'baked-feta-tomatoes', name: 'Baked Feta with Cherry Tomatoes', accent: '#DB2777',
    macros: { protein: 'high', fat: 'high', carb: 'low' }, taste: 'tangy',
    suitableFor: ['adults', 'teenagers'], cookingTime: 'comfort',
    mealTime: ['dinner'],
    benefit: 'A block of feta melts into burst cherry tomatoes — one pan, mostly hands-off, deeply satisfying.',
    time: '40 min', source: 'seed',
    ingredients: ['Feta cheese (400g block)', 'Cherry tomatoes (4 cups)', 'Garlic (6 cloves, peeled)', 'Olive oil (½ cup)', 'Red pepper flakes (1 tsp)', 'Fresh basil (1 cup, torn)', 'Black pepper (1 tsp)', 'Lemon (½, zested)'],
    simpleSteps: [
      'Preheat the oven to 400°F (200°C). In a baking dish, scatter the cherry tomatoes and whole garlic cloves.',
      'Place the whole block of feta in the center, nestled into the tomatoes. Pour olive oil over everything and sprinkle with red pepper flakes and black pepper.',
      'Bake for 30–35 minutes until the tomatoes have burst and the feta is golden on top and creamy underneath.',
      'Pull it out and let it cool for 2 minutes. Use a fork to mash the feta and tomatoes together right in the dish.',
      'Stir in lemon zest and torn basil. Eat with a spoon, or use as a sauce over zucchini noodles or grilled vegetables.',
    ],
    cookingMode: [
      { text: 'Preheat oven to 400°F (200°C).' },
      { text: 'In a medium baking dish, scatter 4 cups cherry tomatoes and 6 peeled garlic cloves.' },
      { text: 'Place the 400g block of feta in the center, nestled into the tomatoes.' },
      { text: 'Pour ½ cup olive oil over everything. Sprinkle 1 tsp red pepper flakes and 1 tsp black pepper.' },
      { text: 'Bake until tomatoes burst and feta is golden on top.', timer: 32, timerLabel: 'Bake' },
      { text: 'Remove from oven. Let it rest.', timer: 2, timerLabel: 'Cool slightly' },
      { text: 'Use a fork to mash the feta and tomatoes together in the dish.' },
      { text: 'Zest ½ lemon over the top and tear in 1 cup fresh basil.' },
      { text: 'Stir gently and serve from the dish.' },
    ],
  },
  {
    id: 'carrot-ginger-soup', name: 'Spiced Carrot & Ginger Soup', accent: '#F97316',
    macros: { protein: 'low', fat: 'low', carb: 'low' }, taste: 'balanced',
    suitableFor: ['adults', 'old', 'kids', 'teenagers'], cookingTime: 'comfort',
    mealTime: ['lunch', 'dinner'],
    benefit: 'Velvety, lean, and warming — ginger and turmeric give this soup quiet healing power.',
    time: '30 min', source: 'seed',
    ingredients: ['Carrots (1 kg, peeled and chopped)', 'Onion (1, diced)', 'Ginger (2 inch piece, grated)', 'Vegetable broth (4 cups)', 'Turmeric (½ tsp)', 'Coconut oil (1 tbsp)', 'Lemon (1, juiced)', 'Cilantro (small handful, chopped)'],
    simpleSteps: [
      'Heat coconut oil in a large pot over medium heat. Add the diced onion and cook for 4 minutes until soft.',
      'Add the grated ginger and turmeric. Cook for 1 minute until very fragrant.',
      'Add the chopped carrots, broth, and a generous pinch of salt. Bring to a boil, then reduce to a simmer.',
      'Cover and cook for 20 minutes until the carrots are completely tender. Test with a fork — they should mash easily.',
      'Blend the soup smooth with an immersion blender. Stir in lemon juice and salt to taste. Top each bowl with cilantro.',
    ],
    cookingMode: [
      { text: 'Peel and chop 1 kg carrots into rough chunks. Dice 1 onion. Grate a 2-inch piece of ginger.' },
      { text: 'Heat 1 tbsp coconut oil in a large pot over medium heat.' },
      { text: 'Add diced onion. Cook until soft and translucent.', timer: 4, timerLabel: 'Soften onion' },
      { text: 'Add the grated ginger and ½ tsp turmeric. Stir.', timer: 1, timerLabel: 'Bloom spices' },
      { text: 'Add the chopped carrots, 4 cups vegetable broth, and a generous pinch of salt.' },
      { text: 'Bring to a boil, then reduce heat and cover. Simmer.', timer: 20, timerLabel: 'Cook carrots' },
      { text: 'Test that carrots mash easily with a fork. If not, simmer 5 more minutes.' },
      { text: 'Use an immersion blender to puree the soup until completely smooth.' },
      { text: 'Stir in juice of 1 lemon. Taste and add more salt if needed.' },
      { text: 'Ladle into bowls. Top with chopped cilantro.' },
    ],
  },
  {
    id: 'banana-almond-smoothie-bowl', name: 'Banana Almond Smoothie Bowl', accent: '#FBBF24',
    macros: { protein: 'low', fat: 'medium', carb: 'high' }, taste: 'sweet',
    suitableFor: ['kids', 'teenagers', 'adults'], cookingTime: 'quick',
    mealTime: ['breakfast', 'snack'],
    benefit: 'Naturally sweet from ripe bananas and dates — no added sugar, just whole-food creaminess.',
    time: '10 min', source: 'seed',
    ingredients: ['Frozen banana (2 large, sliced)', 'Almond milk (½ cup, unsweetened)', 'Almond butter (2 tbsp)', 'Medjool dates (3, pitted)', 'Cinnamon (½ tsp)', 'Sliced almonds (¼ cup)', 'Fresh berries (1 cup)', 'Coconut flakes (2 tbsp)'],
    simpleSteps: [
      'Freeze the banana slices ahead of time — at least 2 hours. This is the secret to the thick ice-cream-like texture.',
      'In a blender, combine frozen banana, almond milk, almond butter, pitted dates, and cinnamon.',
      'Blend until smooth and thick. If too thick, add a splash more almond milk; if too thin, freeze for 10 minutes before serving.',
      'Spoon the smoothie into a wide shallow bowl.',
      'Top with sliced almonds, fresh berries, and coconut flakes arranged neatly in stripes. Eat with a spoon.',
    ],
    cookingMode: [
      { text: 'Note: bananas must already be frozen — at least 2 hours ahead. If not, this is a 2-hour wait.' },
      { text: 'In a blender, combine 2 frozen bananas, ½ cup almond milk, 2 tbsp almond butter, 3 pitted dates, and ½ tsp cinnamon.' },
      { text: 'Blend until thick and smooth — about 60 seconds.', timer: 1, timerLabel: 'Blend' },
      { text: 'Check consistency. Add splash of milk if too thick to scoop. If too thin, freeze 10 min.' },
      { text: 'Spoon the smoothie into a wide shallow bowl.' },
      { text: 'Top with ¼ cup sliced almonds in a stripe.' },
      { text: 'Add 1 cup fresh berries in another stripe.' },
      { text: 'Finish with 2 tbsp coconut flakes. Serve immediately.' },
    ],
  },
  {
    id: 'hummus-vegetable-plate', name: 'Hummus & Vegetable Plate', accent: '#A16207',
    macros: { protein: 'medium', fat: 'high', carb: 'low' }, taste: 'balanced',
    suitableFor: ['adults', 'teenagers', 'kids', 'old'], cookingTime: 'quick',
    mealTime: ['snack', 'lunch'],
    benefit: 'A bright, colorful platter — fresh vegetables with creamy hummus, the original Mediterranean snack.',
    time: '15 min', source: 'seed',
    ingredients: ['Chickpeas (1 can, drained)', 'Tahini (3 tbsp)', 'Garlic (2 cloves)', 'Lemon (1, juiced)', 'Olive oil (3 tbsp)', 'Cucumber (1, sliced into spears)', 'Carrots (3, cut into sticks)', 'Bell pepper (1, sliced)'],
    simpleSteps: [
      'In a food processor, blend drained chickpeas, tahini, garlic cloves, half the lemon juice, and 2 tbsp olive oil.',
      'While blending, add 2–3 tablespoons of cold water until the hummus is smooth and fluffy. Add the rest of the lemon juice and salt to taste.',
      'Scrape into a wide shallow bowl. Use the back of a spoon to swirl the surface and create a well in the center.',
      'Drizzle the remaining olive oil into the well. Optionally dust with paprika or cumin.',
      'Arrange cucumber spears, carrot sticks, and bell pepper slices around the bowl. Dip and enjoy.',
    ],
    cookingMode: [
      { text: 'Drain and rinse 1 can chickpeas.' },
      { text: 'In a food processor, combine chickpeas, 3 tbsp tahini, 2 garlic cloves, and juice of ½ lemon.' },
      { text: 'Add 2 tbsp olive oil and start blending.' },
      { text: 'While running, slowly add 2–3 tbsp cold water until silky smooth.', timer: 2, timerLabel: 'Blend smooth' },
      { text: 'Taste. Add remaining lemon juice and salt as needed.' },
      { text: 'Scrape into a wide shallow bowl. Use the back of a spoon to swirl the surface.' },
      { text: 'Drizzle the remaining 1 tbsp olive oil in the center.' },
      { text: 'Slice 1 cucumber into spears, 3 carrots into sticks, and 1 bell pepper into wedges.' },
      { text: 'Arrange the vegetables around the bowl on a platter. Serve.' },
    ],
  },
  {
    id: 'roasted-spiced-chickpeas', name: 'Roasted Spiced Chickpeas', accent: '#C2410C',
    macros: { protein: 'high', fat: 'medium', carb: 'low' }, taste: 'spicy',
    suitableFor: ['adults', 'teenagers', 'kids'], cookingTime: 'quick',
    mealTime: ['snack'],
    benefit: 'Crunchy, savory, high-protein — the snack that replaces chips without compromise.',
    time: '40 min', source: 'seed',
    ingredients: ['Chickpeas (2 cans, drained)', 'Olive oil (3 tbsp)', 'Cumin (1 tsp)', 'Smoked paprika (1 tsp)', 'Garlic powder (½ tsp)', 'Cayenne (¼ tsp)', 'Sea salt (1 tsp)', 'Black pepper (½ tsp)'],
    simpleSteps: [
      'Preheat the oven to 425°F (220°C). Drain the chickpeas and dry them very thoroughly — really thoroughly. Wet chickpeas steam instead of crisping.',
      'Spread the dried chickpeas on a sheet pan and roast for 20 minutes plain, shaking the pan halfway through.',
      'While they roast, mix the cumin, smoked paprika, garlic powder, cayenne, salt, and pepper in a bowl.',
      'Pull the chickpeas from the oven. Drizzle with olive oil, sprinkle on the spice mix, and toss to coat.',
      'Return to the oven for 8–10 more minutes until deeply crispy. They keep crisping as they cool — so don\'t undercook them.',
    ],
    cookingMode: [
      { text: 'Preheat oven to 425°F (220°C).' },
      { text: 'Drain 2 cans of chickpeas. Spread on a clean kitchen towel.' },
      { text: 'Pat dry very thoroughly — even rub them — to remove every drop of moisture.' },
      { text: 'Transfer to a sheet pan in a single layer. Roast plain (no oil yet) shaking halfway.', timer: 20, timerLabel: 'Initial dry roast' },
      { text: 'While roasting: mix 1 tsp cumin, 1 tsp smoked paprika, ½ tsp garlic powder, ¼ tsp cayenne, 1 tsp salt, ½ tsp black pepper in a bowl.' },
      { text: 'Remove chickpeas. Drizzle with 3 tbsp olive oil. Sprinkle on the spice mix. Toss to coat.' },
      { text: 'Return to oven. Roast until deeply golden and crispy.', timer: 9, timerLabel: 'Final crisp' },
      { text: 'Let cool 5 minutes — they crisp up more as they cool.', timer: 5, timerLabel: 'Cool & crisp' },
    ],
  },
  {
    id: 'tamarind-cabbage-slaw', name: 'Tamarind Cabbage Slaw', accent: '#9F1239',
    macros: { protein: 'low', fat: 'medium', carb: 'low' }, taste: 'sour',
    suitableFor: ['adults', 'teenagers'], cookingTime: 'quick',
    mealTime: ['lunch', 'dinner', 'snack'],
    benefit: 'A bright, sour, crunchy slaw — tamarind brings depth that vinegar slaws never reach.',
    time: '15 min', source: 'seed',
    ingredients: ['Red cabbage (½ head, finely shredded)', 'Carrots (2, julienned)', 'Tamarind paste (2 tbsp)', 'Sesame oil (2 tbsp)', 'Fish-free soy sauce (2 tbsp)', 'Peanuts (¼ cup, roasted)', 'Cilantro (1 cup, chopped)', 'Lime (1, juiced)'],
    simpleSteps: [
      'Shred the red cabbage very thinly — use a mandoline if you have one. Julienne the carrots into matchsticks.',
      'In a small bowl, whisk together tamarind paste, sesame oil, soy sauce, and lime juice. Taste it — it should be sour-savory.',
      'In a large bowl, toss the cabbage and carrots with the dressing. Use your hands and squeeze gently — this helps the cabbage soak up the dressing.',
      'Let it sit for 10 minutes so the flavors mingle. The cabbage will soften slightly but stay crunchy.',
      'Just before serving, toss with chopped cilantro and roasted peanuts for crunch.',
    ],
    cookingMode: [
      { text: 'Shred ½ head red cabbage very thinly. A mandoline helps but a sharp knife works.' },
      { text: 'Julienne 2 carrots into thin matchsticks.' },
      { text: 'In a small bowl, whisk together 2 tbsp tamarind paste, 2 tbsp sesame oil, 2 tbsp soy sauce, and juice of 1 lime.' },
      { text: 'Taste the dressing — it should be sour, salty, and a little nutty. Adjust if needed.' },
      { text: 'In a large bowl, combine the cabbage and carrots.' },
      { text: 'Pour the dressing over and toss thoroughly with your hands, squeezing gently to soften.' },
      { text: 'Let the slaw sit so flavors mingle.', timer: 10, timerLabel: 'Rest' },
      { text: 'Just before serving, toss in 1 cup chopped cilantro and ¼ cup roasted peanuts.' },
    ],
  },
  {
    id: 'cucumber-raita-bowl', name: 'Cucumber Mint Raita Bowl', accent: '#0EA5E9',
    macros: { protein: 'low', fat: 'low', carb: 'low' }, taste: 'balanced',
    suitableFor: ['kids', 'old', 'adults', 'teenagers'], cookingTime: 'quick',
    mealTime: ['lunch', 'snack'],
    benefit: 'Cool, lean, and herbal — yogurt and cucumber soothe spice and summer heat alike.',
    time: '10 min', source: 'seed',
    ingredients: ['Greek yogurt (2 cups)', 'Cucumber (1 large, grated and squeezed)', 'Fresh mint (¼ cup, finely chopped)', 'Cilantro (¼ cup, chopped)', 'Cumin (1 tsp, roasted and ground)', 'Green chili (½, minced — optional)', 'Lemon (½, juiced)', 'Black salt (½ tsp)'],
    simpleSteps: [
      'Grate the cucumber on a coarse grater. Place in a clean cloth and squeeze out as much water as you can — this is essential or the raita gets watery.',
      'In a bowl, whisk the Greek yogurt until smooth and creamy.',
      'Add the squeezed cucumber, chopped mint, cilantro, ground cumin, optional green chili, lemon juice, and black salt.',
      'Stir gently to combine. Taste and adjust salt or lemon as needed.',
      'Chill for 10 minutes before serving — it tastes better cold. Serve as a meal in a bowl with crackers, or alongside any spicy dish.',
    ],
    cookingMode: [
      { text: 'Grate 1 cucumber on a coarse grater.' },
      { text: 'Place grated cucumber in a clean cloth or paper towel. Twist firmly to squeeze out all the water.' },
      { text: 'In a serving bowl, whisk 2 cups Greek yogurt until smooth.' },
      { text: 'Add the squeezed cucumber to the yogurt.' },
      { text: 'Finely chop ¼ cup mint and ¼ cup cilantro. Add to the bowl.' },
      { text: 'Add 1 tsp roasted ground cumin, ½ minced green chili (optional), juice of ½ lemon, and ½ tsp black salt.' },
      { text: 'Stir gently to combine. Taste and adjust seasoning.' },
      { text: 'Chill before serving.', timer: 10, timerLabel: 'Chill' },
    ],
  },
  {
    id: 'tofu-vegetable-stirfry', name: 'Vegetable Stir-fry with Tofu', accent: '#16A34A',
    macros: { protein: 'high', fat: 'low', carb: 'low' }, taste: 'tangy',
    suitableFor: ['adults', 'teenagers'], cookingTime: 'quick',
    mealTime: ['lunch', 'dinner'],
    benefit: 'Lean, vibrant, and fast — a vegetable wok dinner that respects time and waistline.',
    time: '20 min', source: 'seed',
    ingredients: ['Firm tofu (400g, cubed)', 'Broccoli (2 cups, florets)', 'Bell peppers (2, sliced)', 'Snow peas (1 cup)', 'Garlic (4 cloves, minced)', 'Ginger (1 inch, grated)', 'Soy sauce (3 tbsp)', 'Rice vinegar (1 tbsp)'],
    simpleSteps: [
      'Press the tofu between paper towels for 5 minutes to remove excess water, then cube it into 1-inch pieces.',
      'Heat a wok or large pan over high heat. Add a small drizzle of oil and the tofu cubes. Pan-fry until golden on multiple sides, about 5 minutes. Remove and set aside.',
      'In the same pan, stir-fry garlic and ginger for 30 seconds. Add the broccoli florets and stir-fry for 2 minutes — they should turn bright green.',
      'Add the bell peppers and snow peas. Stir-fry for another 2 minutes — vegetables should be tender-crisp, never soggy.',
      'Return the tofu to the pan. Pour in soy sauce and rice vinegar. Toss everything together for 1 minute. Serve immediately.',
    ],
    cookingMode: [
      { text: 'Press 400g firm tofu between paper towels with something heavy on top.', timer: 5, timerLabel: 'Press tofu' },
      { text: 'Cube the pressed tofu into 1-inch pieces.' },
      { text: 'Cut 2 cups broccoli into florets. Slice 2 bell peppers. Mince 4 garlic cloves and grate 1 inch ginger.' },
      { text: 'Heat a wok or wide pan over high heat. Add 1 tsp neutral oil.' },
      { text: 'Add tofu cubes. Pan-fry, turning, until golden on multiple sides.', timer: 5, timerLabel: 'Brown tofu' },
      { text: 'Remove tofu to a plate.' },
      { text: 'In the same pan, add garlic and ginger. Stir-fry for 30 seconds.', timer: 1, timerLabel: 'Aromatics' },
      { text: 'Add broccoli florets. Stir-fry until bright green.', timer: 2, timerLabel: 'Broccoli' },
      { text: 'Add bell peppers and 1 cup snow peas. Stir-fry until tender-crisp.', timer: 2, timerLabel: 'Pepper & peas' },
      { text: 'Return tofu to the pan. Add 3 tbsp soy sauce and 1 tbsp rice vinegar.' },
      { text: 'Toss everything together to coat.', timer: 1, timerLabel: 'Glaze' },
      { text: 'Serve immediately.' },
    ],
  },
  {
    id: 'date-almond-energy-balls', name: 'Date & Almond Energy Balls', accent: '#92400E',
    macros: { protein: 'medium', fat: 'high', carb: 'low' }, taste: 'sweet',
    suitableFor: ['kids', 'teenagers', 'adults'], cookingTime: 'quick',
    mealTime: ['snack', 'breakfast'],
    benefit: 'Naturally sweet from dates — no added sugar, no baking, ready in 10 minutes. Kid-approved.',
    time: '15 min', source: 'seed',
    ingredients: ['Medjool dates (1.5 cups, pitted)', 'Almonds (1 cup, raw)', 'Cashews (½ cup, raw)', 'Cocoa powder (2 tbsp, unsweetened)', 'Vanilla extract (1 tsp)', 'Cinnamon (½ tsp)', 'Sea salt (¼ tsp)', 'Coconut flakes (¼ cup, unsweetened, for rolling)'],
    simpleSteps: [
      'Make sure your dates are soft. If they\'re dry, soak them in warm water for 5 minutes, then drain and pat dry.',
      'In a food processor, pulse the almonds and cashews until they look like coarse crumbs.',
      'Add the dates, cocoa powder, vanilla, cinnamon, and salt. Process until everything comes together into a sticky dough — about 60 seconds.',
      'Roll the dough into 1-inch balls with your hands. Mixture should hold together; if too dry, add 1 date; if too wet, add a spoonful of ground nuts.',
      'Roll each ball in coconut flakes to coat. Refrigerate for at least 30 minutes to firm up — they keep for 2 weeks in the fridge.',
    ],
    cookingMode: [
      { text: 'Check your 1.5 cups Medjool dates. If dry, soak in warm water for 5 minutes, then drain.', timer: 5, timerLabel: 'Soften dates if needed' },
      { text: 'In a food processor, pulse 1 cup almonds and ½ cup cashews until they form coarse crumbs.', timer: 1, timerLabel: 'Crumb the nuts' },
      { text: 'Add the pitted dates, 2 tbsp cocoa powder, 1 tsp vanilla, ½ tsp cinnamon, and ¼ tsp sea salt.' },
      { text: 'Process until a sticky dough forms — about 60 seconds.', timer: 1, timerLabel: 'Process to dough' },
      { text: 'Check consistency. Should hold when pressed. If too dry, add a date; if too wet, add ground nuts.' },
      { text: 'Pour ¼ cup coconut flakes into a shallow bowl.' },
      { text: 'Roll the dough into 1-inch balls — about 16 balls.' },
      { text: 'Roll each ball in coconut flakes until coated.' },
      { text: 'Refrigerate until firm.', timer: 30, timerLabel: 'Chill to firm up' },
    ],
  },
];
// Helper: returns 0 for exact match, 1 for one step off (low↔medium, medium↔high),
// 2 for opposite ends (low↔high).
function macroDistance(a, b) {
  const order = { low: 1, medium: 2, high: 3 };
  return Math.abs((order[a] || 2) - (order[b] || 2));
}

// Helper: score a macro dimension with STRICT penalties.
// User says low? They mean low. Medium gets a real penalty. High is heavily penalized.
function scoreMacro(recipeMacro, prefMacro, bonus) {
  const d = macroDistance(recipeMacro, prefMacro);
  if (d === 0) return bonus;       // exact match: +bonus
  if (d === 1) return -bonus * 1.5; // one step off: significant penalty (was -0.5)
  return -bonus * 3;                // opposite end: heavy penalty (was -2)
}

export function scoreRecipe(recipe, prefs, analytics, currentMealTime = null) {
  let score = 0;

  // Macros now use distance-aware scoring — mismatches get penalized, not just ignored.
  // Carb (your low-carb bug): asked low + recipe high = -4. Asked low + recipe medium = -1. Asked low + recipe low = +2.
  score += scoreMacro(recipe.macros.protein, prefs.protein, 3);
  score += scoreMacro(recipe.macros.fat, prefs.fat, 2);
  score += scoreMacro(recipe.macros.carb, prefs.carb, 2);

  // Taste: a bit softer than macros — exploration is good for taste discovery.
  // Match: +3, mismatch: -1. "balanced" preference matches anything.
  if (prefs.taste === 'balanced' || recipe.taste === prefs.taste) score += 3;
  else score -= 1;

  // Audience: unchanged — still hard penalty if no one at the table fits the recipe.
  const audienceMatch = prefs.audience.some(a => recipe.suitableFor.includes(a));
  if (audienceMatch) score += 4; else score -= 5;

  if (prefs.cookingTime && recipe.cookingTime === prefs.cookingTime) score += 2;

  if (currentMealTime) {
    if (recipe.mealTime?.includes(currentMealTime)) score += 6;
    else score -= 20;
  }

  const a = analytics[recipe.id] || { likes: 0, dislikes: 0, visits: 0, dwellMs: 0 };
  score += a.likes * 2;
  score -= a.dislikes * 3;
  score += Math.min(a.visits, 5) * 0.5;
  score += Math.min(a.dwellMs / 60000, 5) * 0.4;
  return score;
}

// ============================================================
//  LLM client — now also asks for mealTime when set
// ============================================================
export async function fetchLLMRecipe(prefs, feedback, existingNames, mealTime = null) {
  const likedNames = Object.entries(feedback).filter(([, v]) => v === 'like').map(([id]) => existingNames[id]).filter(Boolean).slice(0, 5);
  const dislikedNames = Object.entries(feedback).filter(([, v]) => v === 'dislike').map(([id]) => existingNames[id]).filter(Boolean).slice(0, 5);
  const res = await fetch('/api/suggest', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      prefs, likedRecipes: likedNames, dislikedRecipes: dislikedNames,
      avoidNames: Object.values(existingNames),
      mealTime,
    }),
  });
  if (!res.ok) throw new Error(`Backend ${res.status}`);
  return await res.json();
}
